language: python
python:
   #- 2.7
   - 3.4
install:
   #  APT stuff is below separately
   # 
   # 1. at some point, move all this to requirements.txt; see http://docs.travis-ci.com/user/languages/python/
   # 2. pip is exported for active virtualenv (2.7 or 3.4), no need to change anything :)
   # 3. numpy is pre-installed by travis implicitly
   #
   - pip install --upgrade pip setuptools
   # Install libraries for nosetests
   - pip install h5py
   - pip install pyvtk
   # this seems to be the new active upstream for pyvtk supporting 2.x and 3.x
   - pip install git+https://github.com/pearu/pyvtk.git
   # codecov-python
   - pip install codecov
   # install mupif itself
   - python setup.py install 

#before_script:
#   # see https://github.com/fabric/fabric/blob/master/.travis.yml
#   # for allowing passwordless SSH to localhost
script:
   - ls -l
   - pwd
   - nosetests --rednose -v --with-coverage
   - codecov -F unittests
   - pwd
   - pushd mupif/examples
   - export USE_CODECOV=true
   - /bin/bash testExamples.sh
   - popd
   - codecov -F examples

##
## container-based infrastructure (http://docs.travis-ci.com/user/migrating-from-legacy/)
##
sudo: false
## maybe install NumPy from miniconda in the future: https://gist.github.com/dan-blanchard/7045057
addons:
   apt:
      packages:
         - libblas-dev
         - liblapack-dev
         - libsuitesparse-dev
         - libhdf5-serial-dev
         - gfortran
         - openssh-server
         - openssh-client
         - python-vtk
